vich_uploader:
  db_driver: orm
  metadata:
    type: attribute
  mappings:
    articles:
      uri_prefix: /uploads/articles
      upload_destination: '%kernel.project_dir%/public/uploads/articles'
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
